Bootstrap

In [11]:
from _notebook_bootstrap import bootstrap

repo_root, datasets_root = bootstrap()
repo_root, datasets_root

(PosixPath('/home/user/workspace/datasets-utilities'),
 PosixPath('/home/user/data/datasets'))

Imports

In [12]:
from pathlib import Path
import pandas as pd
import numpy as np
import copy
import pypowsybl as pp
from scipy.io import loadmat
from pypower.api import rundcpf, runpf, ppoption

from dataloaders.rte7000_opensynth import Rte7000OpenSynth

Load dataset object

In [13]:
# Select your file (can be changed to any other snapshot path under datasets_root)
xiidm_relpath = "d_gitt_rte7000_2021/rte-01Jan21-0000.xiidm"

ds = Rte7000OpenSynth(datasets_root=datasets_root, relpath=xiidm_relpath)
xiidm_file = ds.path

Convert to matpower

In [14]:
#input_file = Path("./data/rte-01Jan21-0000.xiidm.bz2").resolve()

out_dir = Path("./converted").resolve()
out_dir.mkdir(exist_ok=True)

# For PyPowSyBl MATPOWER export, use .mat
out_file = out_dir / "rte-01Jan21-0000.mat"

grid = pp.network.load(xiidm_file)
grid.save(out_file, format="MATPOWER")

print("Exported:", out_file)
print("Exists:", out_file.exists())
print("Size:", out_file.stat().st_size, "bytes")

Exported: /home/user/workspace/datasets-utilities/notebooks/converted/rte-01Jan21-0000.mat
Exists: True
Size: 283757 bytes

In [15]:
out_file = Path("./converted/rte-01Jan21-0000.mat").resolve()

mat = loadmat(out_file, squeeze_me=True, struct_as_record=False)

print("Top-level keys:")
print([k for k in mat.keys() if not k.startswith("__")])

Top-level keys:
['mpc']

In [16]:
out_file = Path("./converted/rte-01Jan21-0000.mat").resolve()

mat = loadmat(out_file, squeeze_me=True, struct_as_record=False)

# MATPOWER .mat files usually contain variable "mpc"
if "mpc" not in mat:
    raise KeyError(f"No 'mpc' variable found. Available keys: {[k for k in mat.keys() if not k.startswith('__')]}")

mpc = mat["mpc"]

required = ["baseMVA", "bus", "gen", "branch"]

for field in required:
    if not hasattr(mpc, field):
        raise AttributeError(f"Missing MATPOWER field: {field}")

print("baseMVA:", mpc.baseMVA)
print("bus shape:", mpc.bus.shape)
print("gen shape:", mpc.gen.shape)
print("branch shape:", mpc.branch.shape)

if hasattr(mpc, "gencost"):
    print("gencost shape:", mpc.gencost.shape)
else:
    print("No gencost field")

baseMVA: 100.0
bus shape: (6404, 13)
gen shape: (2242, 21)
branch shape: (8891, 13)
No gencost field

In [17]:
matpower_file = Path("./converted/rte-01Jan21-0000.mat").resolve()
mat = loadmat(matpower_file, squeeze_me=True, struct_as_record=False)
mpc = mat["mpc"]

ppc = {
    "version": "2",
    "baseMVA": float(np.asarray(mpc.baseMVA).squeeze()),
    "bus": np.asarray(mpc.bus, dtype=float),
    "gen": np.asarray(mpc.gen, dtype=float),
    "branch": np.asarray(mpc.branch, dtype=float),
}

bus_cols = [
    "BUS_I", "BUS_TYPE", "PD", "QD", "GS", "BS", "BUS_AREA",
    "VM", "VA", "BASE_KV", "ZONE", "VMAX", "VMIN"
]

gen_cols = [
    "GEN_BUS", "PG", "QG", "QMAX", "QMIN", "VG", "MBASE",
    "GEN_STATUS", "PMAX", "PMIN", "PC1", "PC2", "QC1MIN",
    "QC1MAX", "QC2MIN", "QC2MAX", "RAMP_AGC", "RAMP_10",
    "RAMP_30", "RAMP_Q", "APF"
]

branch_cols = [
    "F_BUS", "T_BUS", "BR_R", "BR_X", "BR_B",
    "RATE_A", "RATE_B", "RATE_C", "TAP", "SHIFT",
    "BR_STATUS", "ANGMIN", "ANGMAX"
]

def nonfinite_report(name, arr, cols):
    arr = np.asarray(arr, dtype=float)
    mask = ~np.isfinite(arr)

    print(f"\n{name}")
    print("shape:", arr.shape)
    print("non-finite cells:", int(mask.sum()))
    print("rows with any non-finite:", int(mask.any(axis=1).sum()))

    counts = mask.sum(axis=0)
    report = pd.DataFrame({
        "col_index": range(arr.shape[1]),
        "column": cols[:arr.shape[1]],
        "nonfinite_count": counts
    })

    display(report[report["nonfinite_count"] > 0])

nonfinite_report("bus", ppc["bus"], bus_cols)
nonfinite_report("gen", ppc["gen"], gen_cols)
nonfinite_report("branch", ppc["branch"], branch_cols)

print("\nBus type counts:")
print(pd.Series(ppc["bus"][:, 1]).value_counts(dropna=False).sort_index())

print("\nGenerator status counts:")
print(pd.Series(ppc["gen"][:, 7]).value_counts(dropna=False).sort_index())

print("\nBranch status counts:")
print(pd.Series(ppc["branch"][:, 10]).value_counts(dropna=False).sort_index())

bus
shape: (6404, 13)
non-finite cells: 7382
rows with any non-finite: 3691

   col_index column  nonfinite_count
2          2     PD             3691
3          3     QD             3691

gen
shape: (2242, 21)
non-finite cells: 2235
rows with any non-finite: 2235

   col_index column  nonfinite_count
1          1     PG             2235

branch
shape: (8891, 13)
non-finite cells: 0
rows with any non-finite: 0

Empty DataFrame
Columns: [col_index, column, nonfinite_count]
Index: []

Bus type counts:
1.0    5934
2.0     469
3.0       1
Name: count, dtype: int64

Generator status counts:
1.0    2242
Name: count, dtype: int64

Branch status counts:
1.0    8891
Name: count, dtype: int64

In [18]:
matpower_file = Path("./converted/rte-01Jan21-0000.mat").resolve()

mat = loadmat(matpower_file, squeeze_me=True, struct_as_record=False)
mpc = mat["mpc"]

ppc = {
    "version": "2",
    "baseMVA": float(np.asarray(mpc.baseMVA).squeeze()),
    "bus": np.asarray(mpc.bus, dtype=float),
    "gen": np.asarray(mpc.gen, dtype=float),
    "branch": np.asarray(mpc.branch, dtype=float),
}

ppc_clean = copy.deepcopy(ppc)

bus = ppc_clean["bus"]
gen = ppc_clean["gen"]
branch = ppc_clean["branch"]

# MATPOWER / PYPOWER column indices
PD = 2
QD = 3
PG = 1

print("Before cleaning:")
print("NaN PD:", np.isnan(bus[:, PD]).sum())
print("NaN QD:", np.isnan(bus[:, QD]).sum())
print("NaN PG:", np.isnan(gen[:, PG]).sum())

# Preserve known values, replace only missing injections
bus[:, PD] = np.nan_to_num(bus[:, PD], nan=0.0)
bus[:, QD] = np.nan_to_num(bus[:, QD], nan=0.0)
gen[:, PG] = np.nan_to_num(gen[:, PG], nan=0.0)

print("\nAfter cleaning:")
print("NaN PD:", np.isnan(bus[:, PD]).sum())
print("NaN QD:", np.isnan(bus[:, QD]).sum())
print("NaN PG:", np.isnan(gen[:, PG]).sum())

print("\nTotals after cleaning:")
print("Total PD:", bus[:, PD].sum())
print("Total QD:", bus[:, QD].sum())
print("Total PG:", gen[:, PG].sum())

print("\nAll finite:")
print("bus:", np.isfinite(bus).all())
print("gen:", np.isfinite(gen).all())
print("branch:", np.isfinite(branch).all())

Before cleaning:
NaN PD: 3691
NaN QD: 3691
NaN PG: 2235

After cleaning:
NaN PD: 0
NaN QD: 0
NaN PG: 0

Totals after cleaning:
Total PD: 0.0
Total QD: 0.0
Total PG: 0.0

All finite:
bus: True
gen: True
branch: True

In [19]:
ppopt_dc = ppoption(
    VERBOSE=2,
    OUT_ALL=1
)

dc_results, dc_success = rundcpf(ppc_clean, ppopt_dc)

print("DC PF success:", dc_success)

bus_res = dc_results["bus"]
branch_res = dc_results["branch"]

print("finite bus results:", np.isfinite(bus_res).all())
print("finite branch results:", np.isfinite(branch_res).all())

print("Va min/max:", np.nanmin(bus_res[:, 8]), np.nanmax(bus_res[:, 8]))

if branch_res.shape[1] >= 17:
    print("Pf min/max:", np.nanmin(branch_res[:, 13]), np.nanmax(branch_res[:, 13]))

PYPOWER Version 5.1.18, 10-Apr-2025 -- DC Power Flow

Converged in 0.02 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses           6404     Total Gen Capacity   92827.7           0.0 to 0.0
Generators      2238     On-line Capacity     92827.7           0.0 to 0.0
Committed Gens  2238     Generation (actual)     -0.0               0.0
Loads              4     Load                     0.0               0.0
  Fixed            0       Fixed                  0.0               0.0
  Dispatchable     4       Dispatchable          -0.0 of 32.7      -0.0
Shunts             0     Shunt (inj)              0.0               0.0
Branches        8891     Losses (I^2 * Z)         0.00              0.00
Transformers    1677     Branch Charging (inj)     -                0.0
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   1.000 p.u. @ bus 1          1.000 p.u. @ bus 1
Voltage Angle      -3.34 deg   @ bus 4809       9.96 deg   @ bus 1957

================================================================================
|     Area Summary                                                             |
================================================================================
Area  # of      # of Gens        # of Loads         # of    # of   # of   # of
 Num  Buses   Total  Online   Total  Fixed  Disp    Shunt   Brchs  Xfmrs   Ties
----  -----   -----  ------   -----  -----  -----   -----   -----  -----  -----
  1    6404    2238   2238       4      0      4       0    8891   1677      0
----  -----   -----  ------   -----  -----  -----   -----   -----  -----  -----
Tot:   6404    2238   2238       4      0      4       0    8891   1677      0

Area      Total Gen Capacity           On-line Gen Capacity         Generation
 Num     MW           MVAr            MW           MVAr             MW    MVAr
----   ------  ------------------   ------  ------------------    ------  ------
  1   92827.7      0.0 to 0.0      92827.7      0.0 to 0.0          -0.0     0.0
----   ------  ------------------   ------  ------------------    ------  ------
Tot:  92827.7      0.0 to 0.0      92827.7      0.0 to 0.0          -0.0     0.0

Area    Disp Load Cap       Disp Load         Fixed Load        Total Load
 Num      MW     MVAr       MW     MVAr       MW     MVAr       MW     MVAr
----    ------  ------    ------  ------    ------  ------    ------  ------
  1       32.7    -0.0      -0.0    -0.0       0.0     0.0       0.0     0.0
----    ------  ------    ------  ------    ------  ------    ------  ------
Tot:      32.7    -0.0      -0.0    -0.0       0.0     0.0       0.0     0.0

Area      Shunt Inj        Branch      Series Losses      Net Export
 Num      MW     MVAr     Charging      MW     MVAr       MW     MVAr
----    ------  ------    --------    ------  ------    ------  ------
  1        0.0     0.0        0.0       0.00    0.00       0.0     0.0
----    ------  ------    --------    ------  ------    ------  ------
Tot:       0.0     0.0        0.0       0.00    0.00       -       -

================================================================================
|     Generator Data                                                           |
================================================================================
 Gen   Bus   Status     Pg        Qg
  #     #              (MW)     (MVAr)
----  -----  ------  --------  --------
  0     19      1        -         -
  1     19      1        -         -
  2     20      1        -         -
  3     96      1        -         -
  4     96      1        -         -
  5    121      1        -         -
  6    158      1        -         -
  7    204      1        -         -
  8    204      1        -         -
  9    233      1        -         -
 10    258      1        -         -
 11    258      1        -         -
 12    258      1        -         -
 13    334      1        -         -
 14    364      1        -         -
 15    364      1        -         -
 16    372      1        -         -
 17    381      1        -         -
 18    382      1        -         -
 19    383      1        -         -
 20    383      1        -         -
 21    397      1        -         -
 22    397      1        -         -
 23    402      1        -         -
 24    402      1        -         -
 25    403      1        -         -
 26    410      1        -         -
 27    410      1        -         -
 28    411      1        -         -
 29    424      1        -         -
 30    424      1        -         -
 31    425      1        -         -
 32    425      1        -         -
 33    426      1        -         -
 34    433      1        -         -
 35    433      1        -         -
 36    433      1        -         -
 37    439      1        -         -
 38    442      1        -         -
 39    442      1        -         -
 40    449      1        -         -
 41    451      1        -         -
 42    451      1        -         -
 43    451      1        -         -
 44    452      1        -         -
 45    452      1        -         -
 46    453      1        -         -
 47    453      1        -         -
 48    454      1        -         -
 49    460      1        -         -
 50    465      1        -         -
 51    468      1        -         -
 52    469      1        -         -
 53    469      1        -         -
 54    469      1        -         -
 55    479      1        -         -
 56    485      1        -         -
 57    486      1        -         -
 58    486      1        -         -
 59    486      1        -         -
 60    489      1        -         -
 61    490      1        -         -
 62    491      1        -         -
 63    491      1        -         -
 64    494      1        -         -
 65    495      1        -         -
 66    496      1        -         -
 67    507      1        -         -
 68    508      1        -         -
 69    508      1        -         -
 70    508      1        -         -
 71    508      1        -         -
 72    508      1        -         -
 73    512      1        -         -
 74    512      1        -         -
 75    512      1        -         -
 76    522      1        -         -
 77    524      1        -         -
 78    525      1        -         -
 79    528      1        -         -
 80    528      1        -         -
 81    532      1        -         -
 82    537      1        -         -
 83    537      1        -         -
 84    543      1        -         -
 85    543      1        -         -
 86    549      1        -         -
 87    549      1        -         -
 88    550      1        -         -
 89    550      1        -         -
 90    550      1        -         -
 91    556      1        -         -
 92    560      1        -         -
 93    561      1        -         -
 94    567      1        -         -
 95    569      1        -         -
 96    572      1        -         -
 97    573      1        -         -
 98    579      1        -         -
 99    580      1        -         -
100    589      1        -         -
101    603      1        -         -
102    603      1        -         -
103    606      1        -         -
104    606      1        -         -
105    608      1        -         -
106    611      1        -         -
107    611      1        -         -
108    612      1        -         -
109    613      1        -         -
110    614      1        -         -
111    626      1        -         -
112    626      1        -         -
113    632      1        -         -
114    632      1        -         -
115    632      1        -         -
116    632      1        -         -
117    634      1        -         -
118    636      1        -         -
119    636      1        -         -
120    639      1        -         -
121    643      1        -         -
122    644      1        -         -
123    644      1        -         -
124    647      1        -         -
125    648      1        -         -
126    648      1        -         -
127    652      1        -         -
128    652      1        -         -
129    654      1        -         -
130    654      1        -         -
131    654      1        -         -
132    659      1        -         -
133    659      1        -         -
134    660      1        -         -
135    660      1        -         -
136    660      1        -         -
137    662      1        -         -
138    666      1        -         -
139    666      1        -         -
140    670      1        -         -
141    670      1        -         -
142    670      1        -         -
143    672      1        -         -
144    672      1        -         -
145    673      1        -         -
146    676      1        -         -
147    678      1        -         -
148    686      1        -         -
149    686      1        -         -
150    687      1        -         -
151    687      1        -         -
152    693      1        -         -
153    700      1        -         -
154    702      1        -         -
155    708      1        -         -
156    714      1        -         -
157    714      1        -         -
159    719      1        -         -
160    719      1        -         -
161    719      1        -         -
162    721      1        -         -
163    721      1        -         -
164    721      1        -         -
165    721      1        -         -
166    724      1        -         -
167    725      1        -         -
168    725      1        -         -
169    728      1        -         -
170    728      1        -         -
171    728      1        -         -
172    728      1        -         -
173    731      1        -         -
174    731      1        -         -
175    732      1        -         -
176    732      1        -         -
177    741      1        -         -
178    753      1        -         -
179    754      1        -         -
180    755      1        -         -
181    755      1        -         -
182    760      1        -         -
183    772      1        -         -
184    772      1        -         -
185    773      1        -         -
186    773      1        -         -
187    774      1        -         -
188    774      1        -         -
189    779      1        -         -
190    779      1        -         -
191    779      1        -         -
192    780      1        -         -
193    783      1        -         -
194    783      1        -         -
197    786      1        -         -
198    793      1        -         -
199    793      1      -0.00      0.00
200    795      1        -         -
201    796      1        -         -
202    802      1        -         -
203    806      1        -         -
204    806      1        -         -
205    806      1        -         -
206    807      1        -         -
207    807      1        -         -
208    808      1        -         -
209    809      1        -         -
210    810      1        -         -
211    810      1        -         -
212    812      1        -         -
213    812      1        -         -
214    813      1        -         -
215    813      1        -         -
216    814      1        -         -
217    816      1        -         -
218    816      1        -         -
219    816      1        -         -
220    817      1        -         -
221    818      1        -         -
222    819      1        -         -
223    819      1        -         -
224    827      1        -         -
225    827      1        -         -
226    828      1        -         -
227    828      1        -         -
228    828      1        -         -
229    836      1        -         -
230    837      1        -         -
231    837      1        -         -
232    838      1        -         -
233    838      1        -         -
234    844      1        -         -
235    851      1        -         -
236    852      1        -         -
237    860      1        -         -
238    860      1        -         -
239    866      1        -         -
240    869      1        -         -
241    871      1        -         -
242    871      1        -         -
243    871      1        -         -
244    880      1        -         -
245    880      1        -         -
246    883      1        -         -
247    887      1        -         -
248    887      1        -         -
249    890      1        -         -
250    902      1        -         -
251    902      1        -         -
252    905      1        -         -
253    905      1        -         -
254    905      1        -         -
255    905      1        -         -
256    906      1        -         -
257    909      1        -         -
258    914      1        -         -
259    914      1        -         -
260    914      1        -         -
261    914      1        -         -
262    920      1        -         -
263    922      1        -         -
264    933      1        -         -
265    933      1        -         -
266    935      1        -         -
267    935      1        -         -
268    937      1        -         -
269    941      1        -         -
270    941      1        -         -
271    943      1        -         -
272    960      1        -         -
273    962      1        -         -
274    962      1        -         -
275    962      1        -         -
276    964      1        -         -
277    967      1        -         -
278    968      1        -         -
279    969      1        -         -
280    970      1        -         -
281    971      1        -         -
282    971      1        -         -
283    977      1        -         -
284    977      1        -         -
285    979      1        -         -
286    980      1        -         -
287    980      1        -         -
288    985      1        -         -
289    985      1        -         -
290    988      1        -         -
291    988      1        -         -
292    990      1        -         -
293    990      1        -         -
294    990      1        -         -
295    990      1        -         -
296    997      1        -         -
297    997      1        -         -
298    997      1        -         -
299    997      1        -         -
300    997      1        -         -
301   1000      1        -         -
302   1007      1        -         -
303   1007      1        -         -
304   1010      1        -         -
305   1016      1        -         -
306   1018      1        -         -
307   1024      1        -         -
308   1034      1        -         -
309   1039      1        -         -
310   1042      1        -         -
311   1042      1        -         -
312   1047      1        -         -
313   1047      1        -         -
314   1047      1        -         -
315   1048      1        -         -
316   1048      1        -         -
317   1048      1        -         -
318   1053      1        -         -
319   1063      1        -         -
320   1064      1        -         -
321   1066      1        -         -
322   1066      1        -         -
323   1067      1        -         -
324   1070      1        -         -
325   1071      1        -         -
326   1072      1        -         -
327   1072      1        -         -
328   1078      1        -         -
329   1085      1        -         -
330   1086      1        -         -
331   1098      1        -         -
332   1098      1        -         -
333   1100      1        -         -
334   1100      1        -         -
335   1100      1        -         -
336   1100      1        -         -
337   1100      1        -         -
338   1100      1        -         -
339   1101      1        -         -
340   1101      1        -         -
341   1101      1        -         -
342   1111      1        -         -
343   1115      1        -         -
344   1115      1        -         -
345   1120      1        -         -
346   1124      1        -         -
347   1124      1        -         -
348   1134      1        -         -
349   1134      1        -         -
350   1135      1        -         -
351   1135      1        -         -
352   1135      1        -         -
353   1138      1        -         -
354   1139      1        -         -
355   1142      1        -         -
356   1152      1        -         -
357   1156      1        -         -
358   1156      1        -         -
359   1157      1        -         -
360   1157      1        -         -
361   1165      1        -         -
362   1166      1        -         -
363   1169      1        -         -
364   1169      1        -         -
365   1169      1        -         -
366   1172      1        -         -
367   1178      1        -         -
368   1178      1        -         -
369   1178      1        -         -
370   1179      1        -         -
371   1179      1        -         -
372   1179      1        -         -
373   1182      1        -         -
374   1182      1        -         -
375   1182      1        -         -
376   1184      1        -         -
377   1184      1        -         -
378   1185      1        -         -
379   1185      1        -         -
380   1186      1        -         -
381   1186      1        -         -
382   1192      1        -         -
383   1192      1        -         -
384   1192      1        -         -
385   1200      1        -         -
386   1210      1        -         -
387   1210      1        -         -
388   1210      1        -         -
389   1210      1        -         -
390   1212      1        -         -
391   1212      1        -         -
392   1215      1        -         -
393   1216      1        -         -
394   1217      1        -         -
395   1218      1        -         -
396   1219      1        -         -
397   1220      1        -         -
398   1220      1        -         -
399   1222      1        -         -
400   1222      1        -         -
401   1224      1        -         -
402   1224      1        -         -
403   1224      1        -         -
404   1226      1        -         -
405   1233      1        -         -
406   1233      1        -         -
407   1234      1        -         -
408   1235      1        -         -
409   1235      1        -         -
410   1235      1        -         -
411   1235      1        -         -
412   1236      1        -         -
413   1238      1        -         -
414   1239      1        -         -
415   1240      1        -         -
416   1269      1        -         -
417   1275      1        -         -
418   1278      1        -         -
419   1280      1        -         -
420   1290      1        -         -
421   1294      1        -         -
422   1294      1        -         -
423   1295      1        -         -
424   1295      1        -         -
425   1295      1        -         -
426   1295      1        -         -
427   1295      1        -         -
428   1295      1        -         -
429   1309      1        -         -
430   1309      1        -         -
431   1309      1        -         -
432   1311      1        -         -
433   1311      1        -         -
434   1313      1        -         -
435   1321      1        -         -

In [20]:
ppopt_ac = ppoption(
    VERBOSE=2,
    OUT_ALL=1,
    PF_ALG=1,
    PF_MAX_IT=100,
    PF_TOL=1e-6
)

ac_results, ac_success = runpf(ppc_clean, ppopt_ac)

print("AC PF success:", ac_success)

bus_res = ac_results["bus"]
branch_res = ac_results["branch"]

print("finite bus results:", np.isfinite(bus_res).all())
print("finite branch results:", np.isfinite(branch_res).all())

print("Vm min/max:", np.nanmin(bus_res[:, 7]), np.nanmax(bus_res[:, 7]))
print("Va min/max:", np.nanmin(bus_res[:, 8]), np.nanmax(bus_res[:, 8]))

if branch_res.shape[1] >= 17:
    print("Pf min/max:", np.nanmin(branch_res[:, 13]), np.nanmax(branch_res[:, 13]))
    print("Qf min/max:", np.nanmin(branch_res[:, 14]), np.nanmax(branch_res[:, 14]))

PYPOWER Version 5.1.18, 10-Apr-2025 -- AC Power Flow (Newton)


 it    max P & Q mismatch (p.u.)
----  ---------------------------
  0         4.903e+02
  1         3.075e+01
  2         9.157e+00
  3         3.244e-01

  4         5.176e-04
  5         1.422e-09
Newton's method power flow converged in 5 iterations.

Converged in 0.21 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses           6404     Total Gen Capacity   92827.7       -27556.3 to 29622.7
Generators      2238     On-line Capacity     92827.7       -27556.3 to 29622.7
Committed Gens  2238     Generation (actual)    125.7           -20421.1
Loads              4     Load                     0.0              13.5
  Fixed            0       Fixed                  0.0               0.0
  Dispatchable     4       Dispatchable          -0.0 of 32.7      13.5
Shunts           123     Shunt (inj)             -0.0           -3549.4
Branches        8891     Losses (I^2 * Z)       125.68           1547.75
Transformers    1677     Branch Charging (inj)     -            25531.7
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   0.766 p.u. @ bus 2731       1.196 p.u. @ bus 3206
Voltage Angle      -4.49 deg   @ bus 4809       8.70 deg   @ bus 5513
P Losses (I^2*R)             -                  4.30 MW    @ line 3205-3206
Q Losses (I^2*X)             -                143.35 MVAr  @ line 3205-3206

================================================================================
|     Area Summary                                                             |
================================================================================
Area  # of      # of Gens        # of Loads         # of    # of   # of   # of
 Num  Buses   Total  Online   Total  Fixed  Disp    Shunt   Brchs  Xfmrs   Ties
----  -----   -----  ------   -----  -----  -----   -----   -----  -----  -----
  1    6404    2238   2238       4      0      4     123    8891   1677      0
----  -----   -----  ------   -----  -----  -----   -----   -----  -----  -----
Tot:   6404    2238   2238       4      0      4     123    8891   1677      0

Area      Total Gen Capacity           On-line Gen Capacity         Generation
 Num     MW           MVAr            MW           MVAr             MW    MVAr
----   ------  ------------------   ------  ------------------    ------  ------
  1   92827.7  -27556.3 to 29622.7  92827.7  -27556.3 to 29622.7     125.7 -20421.1
----   ------  ------------------   ------  ------------------    ------  ------
Tot:  92827.7  -27556.3 to 29622.7  92827.7  -27556.3 to 29622.7     125.7 -20421.1

Area    Disp Load Cap       Disp Load         Fixed Load        Total Load
 Num      MW     MVAr       MW     MVAr       MW     MVAr       MW     MVAr
----    ------  ------    ------  ------    ------  ------    ------  ------
  1       32.7    -0.0      -0.0    13.5       0.0     0.0       0.0    13.5
----    ------  ------    ------  ------    ------  ------    ------  ------
Tot:      32.7    -0.0      -0.0    13.5       0.0     0.0       0.0    13.5

Area      Shunt Inj        Branch      Series Losses      Net Export
 Num      MW     MVAr     Charging      MW     MVAr       MW     MVAr
----    ------  ------    --------    ------  ------    ------  ------
  1       -0.0 -3549.4    25531.7     125.68 1547.75       0.0     0.0
----    ------  ------    --------    ------  ------    ------  ------
Tot:      -0.0 -3549.4    25531.7     125.68 1547.75       -       -

================================================================================
|     Generator Data                                                           |
================================================================================
 Gen   Bus   Status     Pg        Qg
  #     #              (MW)     (MVAr)
----  -----  ------  --------  --------
  0     19      1       0.00     -0.00
  1     19      1       0.00     -0.00
  2     20      1       0.00     -0.00
  3     96      1       0.00     48.83
  4     96      1       0.00     46.37
  5    121      1       0.00    -37.19
  6    158      1       0.00    -11.65
  7    204      1       0.00     -0.00
  8    204      1       0.00     -0.00
  9    233      1       0.00     -8.36
 10    258      1       0.00     -0.00
 11    258      1       0.00     -0.00
 12    258      1       0.00     -0.00
 13    334      1       0.00      0.00
 14    364      1       0.00      0.00
 15    364      1       0.00      0.00
 16    372      1       0.00     83.18
 17    381      1       0.00     -0.00
 18    382      1       0.00      0.00
 19    383      1       0.00      0.00
 20    383      1       0.00      0.00
 21    397      1       0.00     -0.00
 22    397      1       0.00     -0.00
 23    402      1       0.00      0.00
 24    402      1       0.00      0.00
 25    403      1       0.00     -0.00
 26    410      1       0.00     -0.00
 27    410      1       0.00     -0.00
 28    411      1       0.00     -0.00
 29    424      1       0.00     -0.00
 30    424      1       0.00     -0.00
 31    425      1       0.00      0.00
 32    425      1       0.00      0.00
 33    426      1       0.00     -0.00
 34    433      1       0.00      0.00
 35    433      1       0.00      0.00
 36    433      1       0.00      0.00
 37    439      1       0.00      0.00
 38    442      1       0.00     -0.00
 39    442      1       0.00     -0.00
 40    449      1       0.00      0.00
 41    451      1       0.00      0.00
 42    451      1       0.00      0.00
 43    451      1       0.00      0.00
 44    452      1       0.00      0.00
 45    452      1       0.00      0.00
 46    453      1       0.00      0.00
 47    453      1       0.00      0.00
 48    454      1       0.00     -0.00
 49    460      1       0.00      0.00
 50    465      1       0.00     -0.00
 51    468      1       0.00      0.58
 52    469      1       0.00     -0.00
 53    469      1       0.00     -0.00
 54    469      1       0.00     -0.00
 55    479      1       0.00      1.42
 56    485      1       0.00      0.00
 57    486      1       0.00      0.00
 58    486      1       0.00      0.00
 59    486      1       0.00      0.00
 60    489      1       0.00     -0.00
 61    490      1       0.00     -0.00
 62    491      1       0.00     -0.00
 63    491      1       0.00     -0.00
 64    494      1       0.00     -0.00
 65    495      1       0.00     -0.00
 66    496      1       0.00     -0.00
 67    507      1        -         -
 68    508      1       0.00     -0.00
 69    508      1       0.00     -0.00
 70    508      1       0.00     -0.00
 71    508      1       0.00     -0.00
 72    508      1       0.00     -0.00
 73    512      1       0.00     -0.04
 74    512      1       0.00     -0.03
 75    512      1       0.00     -0.17
 76    522      1       0.00      0.00
 77    524      1       0.00      0.00
 78    525      1       0.00      9.73
 79    528      1       0.00      0.00
 80    528      1       0.00      0.00
 81    532      1       0.00      6.48
 82    537      1       0.00     -0.00
 83    537      1       0.00     -0.00
 84    543      1       0.00     -0.00
 85    543      1       0.00     -0.00
 86    549      1        -         -
 87    549      1        -         -
 88    550      1       0.00     -0.00
 89    550      1       0.00     -0.00
 90    550      1       0.00     -0.00
 91    556      1       0.00     -0.23
 92    560      1       0.00     -0.00
 93    561      1       0.00      7.91
 94    567      1       0.00     -1.02
 95    569      1       0.00     -0.00
 96    572      1       0.00     -0.06
 97    573      1       0.00     55.99
 98    579      1       0.00      0.00
 99    580      1       0.00      0.00
100    589      1       0.00    -11.66
101    603      1       0.00      0.14
102    603      1       0.00      0.14
103    606      1       0.00     -0.00
104    606      1       0.00     -0.00
105    608      1       0.00      4.46
106    611      1       0.00      0.00
107    611      1       0.00      0.00
108    612      1       0.00     -0.00
109    613      1       0.00      0.00
110    614      1       0.00      3.10
111    626      1       0.00     -0.00
112    626      1       0.00     -0.00
113    632      1       0.00     -0.00
114    632      1       0.00     -0.00
115    632      1       0.00     -0.00
116    632      1       0.00     -0.00
117    634      1       0.00     -0.00
118    636      1       0.00      0.00
119    636      1       0.00      0.00
120    639      1       0.00     -1.55
121    643      1       0.00      0.00
122    644      1       0.00     -0.00
123    644      1       0.00     -0.00
124    647      1       0.00      0.00
125    648      1       0.00      0.00
126    648      1       0.00      0.00
127    652      1       0.00      0.00
128    652      1       0.00      0.00
129    654      1       0.00     -0.00
130    654      1       0.00     -0.00
131    654      1       0.00     -0.00
132    659      1       0.00     -0.00
133    659      1       0.00     -0.00
134    660      1       0.00     -0.00
135    660      1       0.00     -0.00
136    660      1       0.00     -0.00
137    662      1       0.00     -0.64
138    666      1       0.00     -0.00
139    666      1       0.00     -0.00
140    670      1       0.00     -0.00
141    670      1       0.00     -0.00
142    670      1       0.00     -0.00
143    672      1       0.00      0.00
144    672      1       0.00      0.00
145    673      1       0.00    -17.48
146    676      1       0.00     -0.00
147    678      1       0.00     -0.22
148    686      1       0.00     -0.00
149    686      1       0.00     -0.00
150    687      1       0.00    -15.49
151    687      1       0.00    -16.09
152    693      1       0.00      0.00
153    700      1       0.00      0.00
154    702      1       0.00     -0.00
155    708      1       0.00      0.00
156    714      1       0.00     -0.00
157    714      1       0.00     -0.00
159    719      1       0.00     -0.00
160    719      1       0.00     -0.00
161    719      1       0.00     -0.00
162    721      1       0.00     -2.19
163    721      1       0.00     -2.34
164    721      1       0.00     -2.65
165    721      1       0.00     -2.26
166    724      1       0.00     -1.79
167    725      1       0.00     -0.24
168    725      1       0.00      0.41
169    728      1       0.00      0.00
170    728      1       0.00      0.16
171    728      1       0.00     -0.16
172    728      1       0.00     -0.00
173    731      1       0.00      0.00
174    731      1       0.00      0.00
175    732      1        -         -
176    732      1        -         -
177    741      1       0.00      0.00
178    753      1       0.00   -272.20
179    754      1       0.00     -2.37
180    755      1       0.00     -1.53
181    755      1       0.00     -0.84
182    760      1       0.00      8.91
183    772      1       0.00      4.99
184    772      1       0.00      5.34
185    773      1       0.00      5.03
186    773      1       0.00      5.30
187    774      1       0.00      8.34
188    774      1       0.00      8.27
189    779      1       0.00      0.00
190    779      1       0.00      0.00
191    779      1       0.00      0.00
192    780      1       0.00     -0.00
193    783      1       0.00     -0.00
194    783      1       0.00     -0.00
197    786      1       0.00      6.11
198    793      1       0.00   -266.16
199    793      1     125.68   -266.16
200    795      1       0.00     19.00
201    796      1       0.00      0.00
202    802      1       0.00     -0.17
203    806      1       0.00      2.00
204    806      1       0.00      2.00
205    806      1       0.00      2.00
206    807      1       0.00      0.00
207    807      1       0.00      0.00
208    808      1       0.00      0.00
209    809      1       0.00     -5.95
210    810      1       0.00      0.00
211    810      1       0.00      0.00
212    812      1       0.00      0.00
213    812      1       0.00      0.00
214    813      1       0.00      0.00
215    813      1       0.00      0.00
216    814      1       0.00     -0.00
217    816      1       0.00      0.00
218    816      1       0.00      0.00
219    816      1       0.00      0.00
220    817      1       0.00      0.00
221    818      1       0.00     -0.00
222    819      1       0.00      0.00
223    819      1       0.00      0.00
224    827      1       0.00      0.00
225    827      1       0.00      0.00
226    828      1       0.00     -0.00
227    828      1       0.00     -0.00
228    828      1       0.00     -0.00
229    836      1       0.00   -154.85
230    837      1       0.00   -205.35
231    837      1       0.00   -205.94
232    838      1       0.00    -39.89
233    838      1       0.00    -39.98
234    844      1       0.00     -0.00
235    851      1       0.00      0.00
236    852      1       0.00     -0.00
237    860      1       0.00     -0.00
238    860      1       0.00     -0.00
239    866      1       0.00      0.00
240    869      1       0.00     -0.00
241    871      1       0.00      0.00
242    871      1       0.00      0.00
243    871      1       0.00      0.00
244    880      1       0.00     -0.00
245    880      1       0.00     -0.00
246    883      1       0.00      1.17
247    887      1       0.00     -0.00
248    887      1       0.00     -0.00
249    890      1       0.00      0.00
250    902      1       0.00      0.00
251    902      1       0.00      0.00
252    905      1        -         -
253    905      1        -         -
254    905      1        -         -
255    905      1        -         -
256    906      1       0.00     -0.00
257    909      1       0.00      0.00
258    914      1       0.00      1.33
259    914      1       0.00      1.23
260    914      1       0.00      1.33
261    914      1       0.00      0.44
262    920      1       0.00     -0.00
263    922      1       0.00     12.68
264    933      1       0.00     -0.00
265    933      1       0.00     -0.00
266    935      1       0.00     -3.19
267    935      1       0.00     -3.19
268    937      1       0.00     20.65
269    941      1       0.00      0.23
270    941      1       0.00      0.22
271    943      1       0.00     -3.85
272    960      1       0.00     -0.00
273    962      1       0.00      1.73
274    962      1       0.00      2.31
275    962      1       0.00      1.87
276    964      1       0.00      0.00
277    967      1       0.00   -193.84
278    968      1       0.00   -209.97
279    969      1       0.00   -218.95
280    970      1       0.00   -239.78
281    971      1       0.00   -461.39
282    971      1       0.00   -205.89
283    977      1        -         -
284    977      1        -         -
285    979      1       0.00      1.87
286    980      1       0.00     -0.00
287    980      1       0.00     -0.00
288    985      1       0.00     -0.00
289    985      1       0.00     -0.00
290    988      1       0.00      0.00
291    988      1       0.00      0.00
292    990      1       0.00     -0.00
293    990      1       0.00     -0.00
294    990      1       0.00     -0.00
295    990      1       0.00     -0.00
296    997      1       0.00    -34.70
297    997      1       0.00    -35.79
298    997      1       0.00    -33.33
299    997      1       0.00    -35.79
300    997      1       0.00    -34.70
301   1000      1       0.00      9.05
302   1007      1       0.00     -0.00
303   1007      1       0.00     -0.00
304   1010      1       0.00      0.00
305   1016      1       0.00     -0.00
306   1018      1       0.00     -1.93
307   1024      1       0.00      9.58
308   1034      1       0.00     -0.00
309   1039      1       0.00   -776.05
310   1042      1       0.00      0.00
311   1042      1       0.00      0.00
312   1047      1       0.00     -0.00
313   1047      1       0.00     -0.00
314   1047      1       0.00     -0.00
315   1048      1       0.00      0.00
316   1048      1       0.00      0.00
317   1048      1       0.00      0.00
318   1053      1       0.00      0.00
319   1063      1       0.00     40.05
320   1064      1       0.00     -3.05
321   1066      1       0.00     -0.00
322   1066      1       0.00     -0.00
323   1067      1       0.00     -5.51
324   1070      1       0.00      2.94
325   1071      1       0.00    211.27
326   1072      1       0.00     80.84
327   1072      1       0.00    130.43
328   1078      1       0.00      3.15
329   1085      1       0.00      0.00
330   1086      1       0.00     -8.03
331   1098      1       0.00      1.34
332   1098      1       0.00      1.86
333   1100      1       0.00      0.00
334   1100      1       0.00      0.00
335   1100      1       0.00      0.00
336   1100      1       0.00      0.00
337   1100      1       0.00      0.00
338   1100      1       0.00      0.00
339   1101      1       0.00     -0.00
340   1101      1       0.00     -0.00
341   1101      1       0.00     -0.00
342   1111      1       0.00    -21.02
343   1115      1       0.00      2.69
344   1115      1       0.00      0.65
345   1120      1       0.00     -3.80
346   1124      1       0.00      0.00
347   1124      1       0.00      0.00
348   1134      1       0.00      0.00
349   1134      1       0.00      0.00
350   1135      1       0.00     -0.00
351   1135      1       0.00     -0.00
352   1135      1       0.00     -0.00
353   1138      1       0.00     -0.02
354   1139      1       0.00      0.00
355   1142      1       0.00     -1.13
356   1152      1       0.00  -1195.45
357   1156      1       0.00      0.00
358   1156      1       0.00      0.00
359   1157      1       0.00     -0.00
360   1157      1       0.00     -0.00
361   1165      1       0.00      0.00
362   1166      1       0.00     -0.00
363   1169      1       0.00      3.45
364   1169      1       0.00      3.45
365   1169      1       0.00      2.15
366   1172      1       0.00   -486.74
367   1178      1       0.00    -10.55
368   1178      1       0.00     -9.43
369   1178      1       0.00     -6.87
370   1179      1       0.00    -10.30
371   1179      1       0.00     -8.69
372   1179      1       0.00     -7.87
373   1182      1       0.00     -0.00
374   1182      1       0.00     -0.00
375   1182      1       0.00     -0.00
376   1184      1       0.00      2.92
377   1184      1       0.00      4.52
378   1185      1       0.00      5.37
379   1185      1       0.00      2.87
380   1186      1       0.00      7.67
381   1186      1       0.00     11.34
382   1192      1       0.00      0.64
383   1192      1       0.00      0.08
384   1192      1       0.00      0.07
385   1200      1       0.00     34.21
386   1210      1       0.00      0.00
387   1210      1       0.00      0.00
388   1210      1       0.00      0.00
389   1210      1       0.00      0.00
390   1212      1       0.00     -0.00
391   1212      1       0.00     -0.00
392   1215      1       0.00      0.00
393   1216      1        -         -
394   1217      1       0.00     -0.00
395   1218      1       0.00     -0.00
396   1219      1       0.00      0.00
397   1220      1       0.00      4.24
398   1220      1       0.00      4.24
399   1222      1       0.00      0.00
400   1222      1       0.00      0.00
401   1224      1        -         -
402   1224      1        -         -
403   1224      1        -         -
404   1226      1       0.00      0.16
405   1233      1       0.00     -0.14
406   1233      1       0.00      0.14
407   1234      1       0.00     -2.01
408   1235      1       0.00      2.98